import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision
from torchvision import transforms

from Reference_attacks import fgsm_attack, pgd5_attack, pgd20_attack

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28*28, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 32)
        self.fc4 = nn.Linear(32, 10)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
        x = F.relu(x)
        x = self.fc4(x)
        output = F.log_softmax(x, dim=1)
        return output

def eval_adv_test(model, device, test_loader, attack_method):
    model.eval()
    correct = 0

    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        data = data.view(data.size(0), 28*28)

        # Generate adversarial examples (needs gradients)
        adv_data = attack_method(model, data, target, device=device)

        # Evaluate on adversarial examples (no gradients needed)
        with torch.no_grad():
            output = model(adv_data)
            pred = output.max(1, keepdim=True)[1]
            correct += pred.eq(target.view_as(pred)).sum().item()

    return correct / len(test_loader.dataset)

def main():

    ################################################################################################
    ## Step 1: Specify your model file (generated by Competition.py)
    ################################################################################################

    your_model_file = "1000.pt"  # <-- CHANGE THIS to your model path

    ################################################################################################
    ## Step 2: Select attack suite for defence evaluation
    ##
    ## Choose ONE of the following options:
    ##
    ##   'baseline'  - Test against 3 basic reference attacks (FGSM, PGD-5, PGD-20)
    ##                 Fast testing (~8 seconds), good for quick self-assessment
    ##
    ##   'extended'  - Test against 15 advanced attacks
    ##                 More comprehensive testing (~30 seconds), closer to real-world scenarios
    ##                 Recommended for thorough assessment before final submission
    ################################################################################################

    attack_mode = 'baseline'  # <-- CHANGE THIS to 'baseline' or 'extended'

    ################################################################################################
    ## Attack Suite Configuration
    ################################################################################################

    if attack_mode == 'baseline':
        # Baseline mode: 3 basic reference attacks
        test_attacks = [
            ('FGSM', fgsm_attack),
            ('PGD-5', pgd5_attack),
            ('PGD-20', pgd20_attack),
        ]
        mode_description = "BASELINE (3 reference attacks)"

    elif attack_mode == 'extended':
        # Extended mode: 15 advanced attacks
        test_attacks = []

        try:
            import Extended_attacks as extended_attacks
            extended_attack_fns = extended_attacks.get_all_attacks()
            for i, attack_fn in enumerate(extended_attack_fns, 1):
                test_attacks.append((f'Advanced-{i:02d}', attack_fn))
            mode_description = f"EXTENDED ({len(test_attacks)} advanced attacks)"
        except Exception as e:
            print(f"[ERROR] Could not load extended attacks: {e}")
            print("[INFO] Falling back to baseline attacks...\n")
            test_attacks = [
                ('FGSM', fgsm_attack),
                ('PGD-5', pgd5_attack),
                ('PGD-20', pgd20_attack),
            ]
            mode_description = "BASELINE (fallback mode)"

    else:
        raise ValueError(f"Invalid attack_mode: '{attack_mode}'. Must be 'baseline' or 'extended'")

    ################################################################################################
    ## (Optional) Step 3: Add your own custom attack methods
    ##
    ## Uncomment and modify the code below to test against your own attack implementations
    ################################################################################################

    # def my_custom_attack(model, X, y, device):
    #     """
    #     Your custom attack implementation

    #     Note: Make sure perturbation distance (L_inf norm) STRICTLY < 0.11 (NOT equal to 0.11)
    #     """
    #     epsilon = 0.1
    #     noise = torch.FloatTensor(*X.shape).uniform_(-epsilon, epsilon).to(device)
    #     X_adv = torch.clamp(X + noise, 0.0, 1.0)
    #     return X_adv
    #
    # # Add your custom attack to the test suite
    # test_attacks.append(('MyAttack', my_custom_attack))

    ################################################################################################
    ## Evaluation Process
    ################################################################################################

    # Setup device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(1)

    print("="*80)
    print("COMP219 Assignment - Defence Evaluation")
    print("="*80)
    print(f"Model file: {your_model_file}")
    print(f"Device: {device}")
    print(f"Test mode: {mode_description}")
    print(f"Total attacks: {len(test_attacks)}")
    print("="*80)

    # Load test data
    test_set = torchvision.datasets.FashionMNIST(root='data', train=False, download=True,transform=transforms.Compose([transforms.ToTensor()]))
    test_loader = DataLoader(test_set, batch_size=128, shuffle=False)

    # Load your trained model
    model = Net().to(device)
    model.load_state_dict(torch.load(your_model_file, map_location=device))

    # Evaluate defence against each attack
    num_attacks = len(test_attacks)
    defence_matrix = np.zeros(num_attacks)

    print("\nEvaluating defence robustness...")
    for i, (attack_name, attack_fn) in enumerate(test_attacks):
        print(f"  [{i+1:2d}/{num_attacks}] {attack_name:<15} ... ", end="", flush=True)
        robust_acc = eval_adv_test(model, device, test_loader, attack_fn)
        defence_matrix[i] = robust_acc
        print(f"{robust_acc*100:>6.2f}%")

    # Calculate overall defence score
    defence_score = np.mean(defence_matrix)

    # Display results
    print("\n" + "="*80)
    print("DEFENCE EVALUATION RESULTS")
    print("="*80)
    print(f"\n{'Attack':<20} {'Robust Accuracy'}")
    print("-"*80)
    for i, (attack_name, _) in enumerate(test_attacks):
        print(f"{attack_name:<20} {defence_matrix[i]*100:>6.2f}%")
    print("-"*80)
    print(f"{'Mean (Defence Score)':<20} {defence_score*100:>6.2f}%")
    print("="*80)

    print(f"\nYour Defence Score: {defence_score:.4f}")
    print("\nInterpretation:")
    print("  - Higher score = better defence (more robust model)")
    print("  - Final grading will normalize scores across all students")
    print(f"  - Current mode: {attack_mode}")
    if attack_mode == 'baseline':
        print("  - Tip: Try 'extended' mode for more comprehensive testing")
    else:
        print("  - Extended mode uses diverse attack strategies for realistic assessment")
    print("="*80)

if __name__ == '__main__':
    main()
